# Site settings
title: Sachin Agarwal
name: Sachin Agarwal
tagline: 'Open Source Enthusiast'
#subtitle: Learnings, Ramblings and Rants. In that order.
email: sachinagarwal0499@gmail.com
description: >
  A blog to keep track of my GSoC progress
baseurl: ""
url: "https://sachin-4099.github.io/"
github_username:  sachin-4099
disqus_baseurl: "https://sachin-4099.github.io/"
disqus_shortname: https-sachin-4099-github-io
permalink: :title

excerpt_seperator: <!-break->


# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true
version: 1.1.0

defaults:
  -
    scope:
      path: ""
    values:
      author: "Sachin Agarwal"


# About/contact
author:
  name:             Sachin Agarwal
  github:           sachin-4099
  email:            sachinagarwal0499@gmail.com
  gravatar_md5:     3b17567050e1b78e8f900d32d12f105c

# External gems
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
